variable "env" {}
variable "region" {}
variable "service_name" {}
variable "container_image" {}
variable "container_port" {}
variable "desired_count" {}
variable "subnets" {}
variable "security_group" {}
variable "vpc_id" {}
variable "ssl_certificate_arn" {}
variable "execution_role_arn" {}
variable "task_role_arn" {}
variable "target_group_port" {}
